[package]
name = "my-strategy"
version = "0.1.0"
edition = "2018"

[dependencies]
model = { path = "raic/clients/rust/model", package = "aicup2019-model" }
trans = { path = "raic/clients/rust/model/trans" }
criterion = "0.3"

[profile.release]
debug = true

[features]
dump_examples = []
dump_opponent = []

[[bench]]
name = "simulator"
harness = false
